<?php

namespace App\Infrastructure\Installers;

use App\Domain\Config\StarterConfig;
use App\Domain\Config\StarterContext;

class DocumentationInstaller extends AbstractInstaller
{
    public function id(): string
    {
        return 'documentation';
    }

    public function supports(StarterConfig $config): bool
    {
        return true;
    }

    public function install(StarterContext $context): void
    {
        $config = $context->config;
        $backend = $config->usesMonorepoLayout() ? './apps/backend' : '.';
        $frontend = $config->usesMonorepoLayout() ? './apps/frontend' : '.';

        $this->write($context, 'README.md', $this->readme($config, $backend, $frontend));
        $this->write($context, 'STARTER.md', "# Starter\n\nGenerated by Laravel Starter Builder.\n\nArchitecture: {$config->architecture}\nFrontend: {$config->frontend}\n");
        $this->write($context, 'AI_CONTEXT.md', $this->aiContext($config));
        $this->write($context, 'DATABASE.md', "# Database\n\nDriver: {$config->database}\n\nNever commit secrets. Copy `.env.example` to `.env`.\n");
        $this->write($context, 'DEPLOYMENT.md', "# Deployment\n\nUse the generated Docker and CI configuration when selected.\n");

        if ($config->apiEnabled()) {
            $this->write($context, 'API.md', "# API\n\nVersioned at `/api/v1`.\n\nError shape:\n\n```json\n{ \"message\": \"Validation failed\", \"errors\": {}, \"code\": \"VALIDATION_ERROR\" }\n```\n");
        }

        if ($config->docker !== 'none') {
            $this->write($context, 'DOCKER.md', "# Docker\n\n```bash\ndocker compose up -d\n```\n");
        }

        $this->agentRules($context);
    }

    public function plannedFiles(StarterConfig $config): array
    {
        return ['README.md', 'STARTER.md', 'AI_CONTEXT.md', '.agent/rules/architecture.mdc'];
    }

    private function readme(StarterConfig $config, string $backend, string $frontend): string
    {
        return <<<MD
# {$config->name}

Generated with Laravel Starter Builder.

## Stack

- Laravel {$config->laravelVersion}
- Architecture: {$config->architecture}
- Frontend: {$config->frontend}
- Database: {$config->database}

## Next steps

```bash
cd {$backend}
cp .env.example .env
php artisan key:generate
php artisan migrate
```

Frontend: `{$frontend}`

## AI skills

This project includes agent skills in `.agent/skills/`:

- `laravel` — backend, Eloquent, tests, architecture
- `frontend` — {$config->frontend} UI and CRUD
MD;
    }

    private function aiContext(StarterConfig $config): string
    {
        $patterns = implode(', ', $config->patterns) ?: 'none';

        return <<<MD
# AI Context

- Architecture: {$config->architecture}
- Patterns: {$patterns}
- API: {$config->api}
- Authentication: {$config->authentication}
- Database: {$config->database}
- Frontend: {$config->frontend}
- Testing: {$this->join($config->testing)}

Rules:

- Do not put business logic inside controllers.
- Use Application Actions for business operations when configured.
- Use repositories only where configured.
- Do not bypass domain boundaries.
- Never expose secrets.
- Follow the generated architecture.
- Agent skills live in `.agent/skills/` (Laravel + frontend).
MD;
    }

    private function agentRules(StarterContext $context): void
    {
        $config = $context->config;
        $rules = [
            'architecture' => "Do not put business logic inside controllers.\nUse Application Actions for business operations when selected.\nUse repositories only where configured.\nDo not bypass domain boundaries.\nFollow {$config->architecture}.",
            'backend' => "Prefer Laravel-native features.\nValidate with Form Requests.\nAuthorize with policies.\nNever disable CSRF globally.",
            'frontend' => "Frontend is {$config->frontend}. Prefer TanStack Query or the framework equivalent for server state. Do not create unnecessary global state.",
            'testing' => 'Cover create, read, update, delete, authorization, and validation for generated CRUD.',
            'security' => "Never expose secrets.\nNever recommend unsafe token storage by default.\nVerify webhooks.\nProtect mass assignment.",
        ];

        foreach ($rules as $name => $body) {
            $this->write($context, ".agent/rules/{$name}.mdc", <<<MDC
---
description: {$name} conventions for this generated project
globs:
alwaysApply: true
---

{$body}
MDC);
        }
    }

    /**
     * @param  array<int, string>  $items
     */
    private function join(array $items): string
    {
        return $items === [] ? 'none' : implode(', ', $items);
    }
}
