<?php

return [
    [
        'id' => 'basic',
        'name' => 'Basic',
        'description' => 'Laravel, Blade, SQLite, Pest, Pint, MVC.',
        'config' => [
            'architecture' => 'mvc',
            'frontend' => 'blade',
            'database' => 'sqlite',
            'testing' => ['pest'],
            'codeQuality' => ['pint'],
        ],
    ],
    [
        'id' => 'api',
        'name' => 'API',
        'description' => 'REST API with Sanctum.',
        'config' => [
            'architecture' => 'mvc-service',
            'frontend' => 'blade',
            'api' => 'rest',
            'authentication' => 'sanctum',
            'database' => 'pgsql',
            'docker' => 'development',
            'testing' => ['pest'],
            'codeQuality' => ['pint'],
            'patterns' => ['service'],
        ],
    ],
    [
        'id' => 'react',
        'name' => 'React',
        'description' => 'Laravel API + React.',
        'config' => [
            'architecture' => 'mvc-service',
            'frontend' => 'react',
            'frontendArchitecture' => 'laravel-integrated',
            'api' => 'rest',
            'authentication' => 'sanctum',
            'typescript' => true,
            'stateManagement' => 'tanstack-query',
            'testing' => ['pest', 'vitest'],
        ],
    ],
    [
        'id' => 'next',
        'name' => 'Next.js',
        'description' => 'Laravel API + Next.js App Router.',
        'config' => [
            'architecture' => 'mvc-service',
            'frontend' => 'next',
            'frontendArchitecture' => 'monorepo',
            'api' => 'rest',
            'authentication' => 'sanctum',
            'database' => 'pgsql',
            'cache' => 'redis',
            'docker' => 'development',
            'typescript' => true,
            'stateManagement' => 'tanstack-query',
        ],
    ],
    [
        'id' => 'nuxt',
        'name' => 'Nuxt',
        'description' => 'Laravel API + Nuxt.',
        'config' => [
            'architecture' => 'mvc-service',
            'frontend' => 'nuxt',
            'frontendArchitecture' => 'monorepo',
            'api' => 'rest',
            'authentication' => 'sanctum',
            'database' => 'pgsql',
            'cache' => 'redis',
            'docker' => 'development',
        ],
    ],
    [
        'id' => 'saas',
        'name' => 'SaaS',
        'description' => 'Modular monolith SaaS starter.',
        'config' => [
            'architecture' => 'modular-monolith',
            'frontend' => 'next',
            'frontendArchitecture' => 'monorepo',
            'api' => 'rest',
            'authentication' => 'sanctum',
            'rbac' => 'spatie',
            'tenancy' => 'shared',
            'database' => 'pgsql',
            'cache' => 'redis',
            'queue' => 'redis',
            'payments' => ['stripe'],
            'storage' => 's3',
            'monitoring' => ['sentry'],
            'docker' => 'development',
            'testing' => ['pest'],
            'codeQuality' => ['pint', 'phpstan'],
        ],
    ],
    [
        'id' => 'enterprise',
        'name' => 'Enterprise',
        'description' => 'DDD modular enterprise starter.',
        'config' => [
            'architecture' => 'ddd',
            'frontend' => 'react',
            'frontendArchitecture' => 'monorepo',
            'api' => 'rest-openapi',
            'authentication' => 'passport',
            'rbac' => 'spatie',
            'database' => 'pgsql',
            'cache' => 'redis',
            'queue' => 'redis',
            'storage' => 's3',
            'monitoring' => ['sentry'],
            'docker' => 'development',
            'cicd' => 'github-actions',
            'testing' => ['pest'],
            'codeQuality' => ['pint', 'phpstan', 'rector'],
        ],
    ],
    [
        'id' => 'ecommerce',
        'name' => 'E-commerce',
        'description' => 'Commerce-oriented modular starter.',
        'config' => [
            'architecture' => 'modular-monolith',
            'frontend' => 'next',
            'frontendArchitecture' => 'monorepo',
            'api' => 'rest',
            'authentication' => 'sanctum',
            'authGuards' => ['customer', 'admin'],
            'rbac' => 'spatie',
            'database' => 'pgsql',
            'cache' => 'redis',
            'queue' => 'redis',
            'storage' => 's3',
            'payments' => ['stripe', 'bkash', 'nagad'],
            'notifications' => ['mail', 'database'],
            'monitoring' => ['audit'],
            'docker' => 'development',
            'testing' => ['pest'],
        ],
    ],
];
